version: "3.8"
services:
  app:
    build: .
    container_name: my-ts-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
volumes:
  mongo_data:
