apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: boyastro/app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: STRIPE_SECRET_KEY
              value: sk_test_51RgjJ6Rkaxke7LhDpjIbwnErFMVfJlzRdByCqvDqwhAEqVNg8UXGiqqVxDgCeA3H99i9MH0Eh0Pk3b4Tc8JXecwQ00E0wlJfct
            - name: STRIPE_WEBHOOK_SECRET
              value: whsec_d5f325b23416c3e096f5b62ba5aff658f1744328596b84bf4b43085b3828e012
            - name: MONGO_URI
              value: "mongodb+srv://game:Thanhdat%401234@cluster0.l4tli.mongodb.net/gamedata"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIA3FER3VEGL3RUNJ7S"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: AWS_REGION
              value: "ap-southeast-1"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 3000
      targetPort: 3000
